### ISSUE TITLE
alo

### ISSUE THREAD

**Issue by 1exsize1** [CADindustries/studicad-docs#2]
Alo there are some problems with this zalupa. It doesn't work at all, when I enter I see ebalo on the background and the app says that something goes wrong and i don't have internet connection. BUT I HAVE INTERNET CONNECTION WTF bLYA. Please fix it and
![image](https://user-images.githubusercontent.com/77006100/172187815-004de133-84d8-4a41-bd30-bbf93cfbc99f.png)

**Comment by CrackAndDie** [comment]
hellooo, nice to meet you too. its ok, that app doesn't work. possible solutions- 
1. Try to stop watching anime
2. Try to stop sitting near Eldar
3. Try to remove toolcad and don't use it
Hope this will help you. see ya later 💯

**Comment by 1exsize1** [comment]
Helo brother my name is Nice to meet you, really useful adviceS, really want to try it. And if we are talking about anime, I like to watch garem, like: obshaga bogindan and the same. About Eldar, he really zaebal(annoys)  me because ti kokos and he oret every minute. Don't know what to talk about the last advice, because i don't want to delete/ Have a nice trip, see you Russia

**Comment by CrackAndDie** [comment]
okau, i wanna kushat, so i don't want to talk with you anymore. see ya in Fanil2 

- [x] anime
- [ ] crfhcjjjkkkk
i am going to close this isue

**Comment by 1exsize1** [comment]
eeeeeeeeeeeeeee, why u closed this i don't know how to call it. It was really nice to talk with u 2day Vrother, and i wanna to kushat' 2/ bye
